import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import Button from "~/components/Button.tsx";
import CategorySlider from "~/components/CategorySlider.tsx";
import TodayBestDeals from "~/components/TodayBestDeals.tsx";
import SalesImage from "~/components/SalesImage.tsx";
import DiscountCard from "~/components/DiscountCard.tsx";

import MainContainer from "./MainContainer";

export default function Main() {

  return (
       <>
          <Head>
            <title>Home</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main className="flex min-h-screen flex-col gap-12 bg-white">
              <div className="relative">
                  <div
                        className="absolute inset-0 z-7 font-inter text-[#333] text-base leading-[20px] box-border text-right transform translate-x-[0vw] translate-y-0 scale-100 rotate-x-0 rotate-y-0 rotate-0 skew-x-0 skew-y-0 transform-style-[preserve-3d]">
                        <img className="bg-blue-200" src="https://uploads-ssl.webflow.com/63e857eaeaf853471d5335ff/63e9b930e006824963189865_bg-stage.png" loading="lazy" sizes="(max-width: 1439px) 100vw, 1440px" srcset="https://uploads-ssl.webflow.com/63e857eaeaf853471d5335ff/63e9b930e006824963189865_bg-stage-p-500.png 500w, https://uploads-ssl.webflow.com/63e857eaeaf853471d5335ff/63e9b930e006824963189865_bg-stage-p-800.png 800w, https://uploads-ssl.webflow.com/63e857eaeaf853471d5335ff/63e9b930e006824963189865_bg-stage-p-1080.png 1080w, https://uploads-ssl.webflow.com/63e857eaeaf853471d5335ff/63e9b930e006824963189865_bg-stage.png 1440w" alt="" />
                  </div>
                  <div className="flex-grow max-h-[70vh] flex flex-col justify-center h-screen relative text-green-900 z-100 mx-14">
                      <h1 className="font-bold text-5xl my-4">Shopping and</h1>
                      <h1 className="font-bold text-5xl my-4">department store.</h1>
                      <h4 className="font-inter text-lg">Gjeni çdo gjë që ju nevojitet online në çdo kohë!</h4>
                       <div className="z-100 self-start transform translate-y-20">
                             <Button green>Learn more</Button>
                      </div>
                  </div>
              </div>
          </main>
          <div className="bg-white">
              <CategorySlider />
              <TodayBestDeals />
              {/*<SalesImage />*/}
          </div>
          <div className="bg-white grid grid-cols-1 gap-1">
              <div>
                <DiscountCard />
              </div>
              <div>
                {/*<SalesImage />*/}
              </div>
          </div>
          <MainContainer />
        </>
  );
}